### ISSUE TITLE
Weather display changes position & zoom

### ISSUE THREAD

**Issue by malcolmh** [OpenNauticalChart/online_map#17]
The weather map should inherit the current position & zoom of the nautical chart.

**Comment by OlafHannemann** [comment]
To inherit the current position should be easy. The zoom level is a little bit more difficult, because we have not all zoom levels available (only 4 to 7). A solution will be to zoom to the nearest available level with out changing the cookie. Most users want to return to their old zoom level when switching back to the base map.
